# Generated by Django 3.2.9 on 2022-05-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(default='All', max_length=100, verbose_name='Tag')),
                ('date', models.DateField(auto_now_add=True)),
                ('header', models.CharField(max_length=100, verbose_name='Heading')),
                ('slug', models.SlugField(editable=False)),
                ('description', models.TextField(default='', max_length=5000, verbose_name='description')),
                ('image', models.ImageField(upload_to='', verbose_name='Image')),
            ],
        ),
    ]
