# Generated by Django 3.2.9 on 2022-06-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(),
        ),
    ]
